### ISSUE TITLE
java.lang.SecurityException

### ISSUE THREAD

**Issue by Shineee** [jp1017/AndroidSerialPort#5]
05-29 00:59:45.879 13200-13200/android.serialport W/System.err: java.lang.SecurityException
05-29 00:59:45.880 13200-13200/android.serialport W/System.err:     at android.serialport.SerialPort.<init>(SerialPort.java:59)
05-29 00:59:45.881 13200-13200/android.serialport W/System.err:     at android.serialport.MyserialActivity$1.onClick(MyserialActivity.java:34)
05-29 00:59:45.882 13200-13200/android.serialport W/System.err:     at android.view.View.performClick(View.java:4444)
05-29 00:59:45.882 13200-13200/android.serialport W/System.err:     at android.view.View$PerformClick.run(View.java:18440)
05-29 00:59:45.883 13200-13200/android.serialport W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
05-29 00:59:45.883 13200-13200/android.serialport W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-29 00:59:45.884 13200-13200/android.serialport W/System.err:     at android.os.Looper.loop(Looper.java:136)
05-29 00:59:45.884 13200-13200/android.serialport W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5016)
05-29 00:59:45.885 13200-13200/android.serialport W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
05-29 00:59:45.886 13200-13200/android.serialport W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
05-29 00:59:45.886 13200-13200/android.serialport W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
05-29 00:59:45.887 13200-13200/android.serialport W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
05-29 00:59:45.887 13200-13200/android.serialport W/System.err:     at dalvik.system.NativeStart.main(Native Method)
05-29 00:59:45.888 13200-13200/android.serialport D/AndroidRuntime: Shutting down VM
点击打开串口，程序崩溃，查看日志，是权限不够，看一下吧，谢谢

**Comment by Shineee** [comment]
Android 4.4.4

**Comment by Shineee** [comment]
解决了，需要root权限才可以，如果还不行，就看看串口名称对不对，一般都是写的不对，导致串口不可写，adb shell看一下就行了
